#!/usr/bin/env python3
"""LinkedIn Post Generator - Creates Unique Content Every Time"""

import random
from datetime import datetime
from pathlib import Path

# Content templates
INTROS = [
    "🎉 Exciting news!",
    "🚀 Big milestone achieved!",
    "💡 Innovation update!",
    "✨ Proud to share!",
    "🔥 Hot off the press!",
    "📢 Announcement time!",
    "🌟 Check this out!",
    "💼 Business update!",
]

BODY_TEMPLATES = [
    """My AI Employee just achieved {tier}!

It's working 24/7 to automate my business and personal tasks.

Key features:
✅ {feature1}
✅ {feature2}
✅ {feature3}

Built with Qwen Code, Python, and MCP servers.""",

    """Just completed {tier} of my AI Employee project!

This autonomous agent handles:
✅ {feature1}
✅ {feature2}
✅ {feature3}

The future of work is here! 🤖""",

    """{tier} - DONE! ✅

My AI Employee now:
✅ {feature1}
✅ {feature2}
✅ {feature3}

Productivity level: 📈📈📈

#AI #Automation #Productivity""",

    """Building an AI Employee that works 24/7!

Latest achievement: {tier}

What it does:
✅ {feature1}
✅ {feature2}
✅ {feature3}

Game changer! 🚀""",
]

FEATURES = [
    "Gmail monitoring & auto-replies",
    "LinkedIn auto-posting",
    "File system automation",
    "Approval workflows",
    "Task scheduling",
    "Smart notifications",
    "Document processing",
    "Email triage",
    "Calendar management",
    "Data extraction",
]

HASHTAGS = [
    ["#AI", "#Automation", "#Business", "#Technology"],
    ["#Innovation", "#Productivity", "#DigitalTransformation"],
    ["#FutureOfWork", "#AI", "#Entrepreneurship"],
    ["#TechNews", "#AI", "#Business", "#Startup"],
    ["#Automation", "#AI", "#MachineLearning", "#Tech"],
]

def generate_post_content():
    """Generate unique LinkedIn post content"""
    
    # Pick random elements
    intro = random.choice(INTROS)
    body_template = random.choice(BODY_TEMPLATES)
    hashtags = random.choice(HASHTAGS)
    
    # Tier based on progress
    tier = "Silver Tier"  # Can be Bronze, Silver, Gold
    
    # Pick 3 random features
    selected_features = random.sample(FEATURES, 3)
    
    # Fill template
    content = body_template.format(
        tier=tier,
        feature1=selected_features[0],
        feature2=selected_features[1],
        feature3=selected_features[2]
    )
    
    # Combine
    full_post = f"{intro}\n\n{content}\n\n{' '.join(hashtags)}"
    
    return full_post


def create_linkedin_request():
    """Create LinkedIn post request in Needs_Action folder"""
    
    vault_path = Path(__file__).parent / "AI_Employee_Vault"
    needs_action = vault_path / "Needs_Action"
    
    # Generate unique content
    content = generate_post_content()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Create request file
    request_file = needs_action / f"LINKEDIN_Post_{timestamp}.md"
    
    request_content = f"""---
type: linkedin_post_request
created: {datetime.now().isoformat()}
status: pending
priority: normal
post_id: {timestamp}
requires_approval: true
---

# LinkedIn Post Request

## Details
- **Type:** Social Media Post
- **Platform:** LinkedIn
- **Status:** Pending Review
- **Requires Approval:** Yes
- **Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Content

{content}

---

## Workflow

1. **Review** this post content
2. **Approve** by moving to `/Approved/Social_Media/` folder
3. **AI will post** automatically after approval
4. **Move to `/Done/`** after posting

---

## To Approve

Move this file to: `/Approved/Social_Media/`

## To Reject

Move this file to: `/Rejected/`

---

*Generated by AI Employee - LinkedIn Post Generator*
*Each post is unique!*
"""
    
    # Write file
    request_file.write_text(request_content, encoding='utf-8')
    
    print("\n" + "=" * 60)
    print("✅ LinkedIn Post Request Created!")
    print("=" * 60)
    print(f"\n📄 File: {request_file.name}")
    print(f"\n📝 Content Preview:")
    print("-" * 60)
    print(content)
    print("-" * 60)
    print(f"\n📍 Location: AI_Employee_Vault/Needs_Action/")
    print("\nNext steps:")
    print("1. Review the content")
    print("2. Move to /Approved/Social_Media/ to publish")
    print("3. Run: python linkedin_auto_post_semi.py")
    print("=" * 60)
    
    return request_file


if __name__ == "__main__":
    create_linkedin_request()
    input("\nPress Enter to exit...")
